### PR TITLE
prov/gni: disallow FI_REMOTE_CQ_DATA w/FI_MORE

### LINKED ISSUE #1110: FI_REMOTE_CQ_DATA does not work with FI_MORE
We need to disable chaining requests with FI_MORE if FI_REMOTE_CQ_DATA is used.  

The FI_REMOTE_CQ_DATA request flag indicates that a transaction should be accompanied with a remote CQ event.  That event is not delivered by the current FI_MORE chaining implementation.  At a minimum, we need to prevent a request from being chained with FI_MORE when  remote CQ data is requested so we are to spec.

### PR DESCRIPTION
**Pull request by a-abraham**
FI_MORE cannot currently support FI_REMOTE_CQ_DATA.
This commit will disallow requests with said flag from
being added to the fi_more list.

fixes ofi-cray/libfabric-cray#1110

Signed-off-by: Amith Abraham <aabraham@cray.com>

### CODE REVIEW

**Comment by sungeunchoi** [comment]
Requesting test program.

**Comment by hppritcha** [comment]
@a-abraham will have Time to add test?

File: prov/gni/src/gnix_rma.c [hunk 1]
```diff
@@ -1352,8 +1352,10 @@ ssize_t _gnix_rma(struct gnix_fid_ep *ep, enum gnix_fab_req_type fr_type,
 	}
 
 	/* Adding FI_FENCE to an FI_MORE list will break the FI_MORE Chain.
-	 * Remove FI_MORE flag when FI_FENCE flag is present. */
-	if (flags & FI_FENCE) {
+	 * Current FI_MORE implementation does not create remote CQ events.
+	 * Remove FI_MORE flag when FI_FENCE or FI_REMOTE_CQ_DATA flags are
+	 * present. */
+	if ((flags & FI_FENCE) || (flags & FI_REMOTE_CQ_DATA)) {
```
Comment (ztiffany) [inline prov/gni/src/gnix_rma.c]: I think you also need to check for:

req->vc->peer_caps & FI_RMA_EVENT

In this case, we send an event to the target to increment a remote counter.  We don't support that with FI_MORE.

Once that's done you should be able to remove the 'fi_more_set' workaround from our criterion tests.

Comment (a-abraham) [reply prov/gni/src/gnix_rma.c]: Just rebased and i'm not seeing any issues. 

However I tried the following change and some corresponding code to remove this case from being queued on the FI_MORE list
```
- if ((flags & FI_FENCE) || (flags & FI_REMOTE_CQ_DATA)) {
+       if ((flags & FI_FENCE) || (flags & FI_REMOTE_CQ_DATA) ||
+           (ep->vc->peer_caps & FI_RMA_EVENT)) {
                flags &= ~FI_MORE;
        }
```
But I'm observing failures on a lot of gnitests afterwards. Trying to figure out why that might be happening...

Comment (a-abraham) [reply prov/gni/src/gnix_rma.c]: This has now been added and works successfully.

**Review by sungeunchoi — APPROVED** [review]

File: prov/gni/src/gnix_rma.c [hunk 2]
```diff
@@ -1452,14 +1446,28 @@ ssize_t _gnix_rma(struct gnix_fid_ep *ep, enum gnix_fab_req_type fr_type,
...
-	 * reqs to the fi_more list. */
-	if ((flags & FI_MORE) || (!(flags & FI_FENCE) &&
-	   (!(slist_empty(&ep->more_write)) ||
-	    !(slist_empty(&ep->more_read))))) {
+	 * it is the first message without FI_MORE.
+	 * Do not add reqs with FI_FENCE or FI_REMOTE_CQ_DATA reqs to
+	 * the fi_more list. */
+	if ((flags & FI_MORE) ||
+	    (!(flags & FI_FENCE) && !(flags & FI_REMOTE_CQ_DATA) &&
+	     !(req->vc->peer_caps & FI_RMA_EVENT) &&
```
Comment (ztiffany) [inline prov/gni/src/gnix_rma.c]: Aren't these checks redundant?

Comment (ztiffany) [inline prov/gni/src/gnix_rma.c]: aren't these two lines just:

!(flags & FI_MORE)

so:

```
if (has_more || (!has_more && has_more_reqs))
    add to more list
```

File: prov/gni/src/gnix_rma.c [hunk 3]
```diff
@@ -1497,9 +1505,10 @@ ssize_t _gnix_rma(struct gnix_fid_ep *ep, enum gnix_fab_req_type fr_type,
 			slist_init(&ep->more_read);
 		}
 
-		/* Requests with FI_FENCE are not added to the FI_MORE List.
-		 * They must be queued separately. */
-		if (flags & FI_FENCE) {
+		/* Requests with FI_FENCE or REMOTE EP requirements are not
+		 * added to the FI_MORE List. They must be queued separately. */
+		if ((flags & FI_FENCE) || (flags & FI_REMOTE_CQ_DATA) ||
+		    (req->vc->peer_caps & FI_RMA_EVENT)) {
```
Comment (ztiffany) [inline prov/gni/src/gnix_rma.c:1511]: Same as above.  Could this be:
```
if (!(flags & FI_MORE))
```

File: prov/gni/src/gnix_rma.c (hunk 2 above)
Comment (a-abraham) [reply prov/gni/src/gnix_rma.c]: That is the general idea - however it's a little more nuanced right?
```
if (has_more ||  
     (!has_more  && has_more_reqs && !(FI_FENCE || FI_REMOTE_CQ_DATA || FI_RMA_EVENT)) 
      add to more list
```
I do think I will edit this to make it more readable. Let me know if I've missed the point of your comment though

File: prov/gni/src/gnix_rma.c (hunk 3 above)
Comment (a-abraham) [reply prov/gni/src/gnix_rma.c:1511]: Wouldn't this capture the first message without FI_MORE (which we don't want to queue separately) ?

File: prov/gni/src/gnix_rma.c (hunk 2 above)
Comment (ztiffany) [reply prov/gni/src/gnix_rma.c]: that code is different than what we have.  I see this (added parens):

if (has_more ||  
     (!has_more  && **(** has_more_reqs && !(FI_FENCE || FI_REMOTE_CQ_DATA || FI_RMA_EVENT) **)** ) 
      add to more list

File: prov/gni/src/gnix_rma.c (hunk 3 above)
Comment (ztiffany) [reply prov/gni/src/gnix_rma.c:1511]: Queued separately, ok makes sense now.

File: prov/gni/src/gnix_rma.c (hunk 2 above)
Comment (a-abraham) [reply prov/gni/src/gnix_rma.c]: If you distribute the && through the parens that's the same as above right?
That being said, like I mentioned it is messy and I'm going to update that real quick.

File: prov/gni/src/gnix_rma.c [hunk 4]
```diff
@@ -1452,14 +1446,28 @@ ssize_t _gnix_rma(struct gnix_fid_ep *ep, enum gnix_fab_req_type fr_type,
...
+	 * Current FI_MORE implementation does not create remote CQ events.
+	 * Remove FI_MORE flag when FI_FENCE or REMOTE EP requirements are
+	 * present. */
+
+	if ((flags & FI_FENCE) || (flags & FI_REMOTE_CQ_DATA) ||
+	    (req->vc->peer_caps & FI_RMA_EVENT)) {
+		flags &= ~FI_MORE;
+	}
+
+
```
Comment (ztiffany) [inline prov/gni/src/gnix_rma.c]: Multiple blank lines added.

**Comment by ztiffany** [comment]
I think I get it now.  It's pretty complicated since we try to treat "more-able" requests without FI_MORE and "non-more-able" requests without FI_MORE differently

**Review by ztiffany — APPROVED** [review]

File: prov/gni/src/gnix_rma.c (hunk 2 above)
Comment (a-abraham) [reply prov/gni/src/gnix_rma.c]: How does this logic look to you @ztiffany   checks out with what we discussed above?
Formatting it well is weird though
```
 if ((flags & FI_MORE) ||
     (!(flags & FI_MORE) &&
     (!slist_empty(&ep->more_write) || !slist_empty(&ep->more_read)) &&
     !(flags & FI_FENCE || flags & FI_REMOTE_CQ_DATA || req->vc->peer_caps & FI_RMA_EVENT)))
```

**Comment by a-abraham** [comment]
@ztiffany  I've added the code that disallows FI_MORE prior to a connection having been established, and have also updated the tests. One last review might be good, but I think we're done here.

**Comment by ztiffany** [comment]
@a-abraham looks good.
