### PR TITLE
prov/gni: fix api_cq test

### LINKED ISSUE #819: api_cq/msg crashes periodically during teardown
The api_cq/msg test reports the following warning and then crashes:

```
libfabric:gni:ep_data:__nic_get_completed_txd():464<warn> [5005:1] CQ error status: SOURCE_SSID:AT_PF_INV:CPLTN_DREQ
[----] Warning! The test `api_cq::msg` crashed during its setup or teardown.
```

I was able to repro about 1 in 5 tries.  Unfortunately criterion does not report it as failing or crashing, so it's easy to miss.  Not sure how long it's been there.

### PR DESCRIPTION
**Pull request by chuckfossen**
fixes ofi-cray/libfabric-cray#819

Signed-off-by: Chuck Fossen <chuckf@cray.com>

### CODE REVIEW

File: prov/gni/test/api_cq.c [hunk 1]
```diff
@@ -268,6 +269,7 @@ int api_cq_check_data(char *buf1, char *buf2, int len)
 
 void api_cq_send_allowed(ssize_t sz, uint64_t flags, char *fn)
 {
+	/* cr_log_info("%s flags:%lx sz:%ld", fn, flags, sz); */
```
Comment (jshimek) [inline prov/gni/test/api_cq.c]: Did you mean to leave this in the commit?

File: prov/gni/test/api_cq.c [hunk 2]
```diff
@@ -291,6 +293,47 @@ void api_cq_recv_allowed(ssize_t sz, uint64_t flags, char *fn)
...
+		if (ret == 1) {
+			source_done = 1;
+		}
+
+		ret = fi_cq_read(cq1, &d_cqe, 1);
+		if (ret == 1) {
+			dest_done = 1;
+		}
+
+		pthread_yield();
```
Comment (jshimek) [inline prov/gni/test/api_cq.c]: Do you need to use pthread_yield here? Since this is not a kernel module where busy spinning is frowned upon it shouldn't impact the application in user space.

File: prov/gni/test/api_cq.c [hunk 3]
```diff
@@ -291,6 +291,43 @@ void api_cq_recv_allowed(ssize_t sz, uint64_t flags, char *fn)
...
 
+void api_cq_wait1(struct fid_cq *cq0, uint64_t cq_bind_flags)
+{
+	int ret;
+	struct fi_cq_tagged_entry cqe;
+
+	if (!cq_bind_flags)
+		return;
+
+	while ((ret = fi_cq_read(msg_cq[0], &cqe, 1)) == -FI_EAGAIN);
```
Comment (jshimek) [inline prov/gni/test/api_cq.c:302]: fi_cq_read can return with a -errno that is not -FI_EAGAIN. Do you want to handle that error case because if you don't handle it the test will move on even though an error occured.

Comment (sungeunchoi) [reply prov/gni/test/api_cq.c:302]: To address this, you can add cr_assert(ret > 0) after the loop.

**Comment by sungeunchoi** [comment]
So what exactly was the cause of the seg fault?

**Comment by chuckfossen** [comment]
We have transactions in flight while tearing down endpoints.
I didn't want to spend a lot of time narrowing it down.
I assume it's related to the work Zach was doing to shut down endpoints cleanly.
I can look at it more closely if you'd like.

**Comment by sungeunchoi** [comment]
No that's fine.  Can you put that into the commit message?  That way if we have a similar problem with another test, we have a chance of finding some info about it in the logs.

**Review by sungeunchoi — APPROVED** [review]
