### PR TITLE
prov/gni: Fix error exit path for fi_endpoint

### LINKED ISSUE #952: fi_endpoint returns FI_SUCCESS on error
The error code in the return value is getting clobbered on the 'err' return path via calls to _gnix_cm_nic_free and _gnix_nic_free (which both always return FI_SUCCESS for non-null arguments):

```
err:
    if (ep_priv->xpmem_hndl) {
            if (_gnix_xpmem_handle_destroy(ep_priv->xpmem_hndl) !=
                FI_SUCCESS) {
                    GNIX_WARN(FI_LOG_EP_CTRL,
                              "_gnix_xpmem_handle_destroy returned %s\n",
                              fi_strerror(-ret));
            }
    }

    __destruct_tag_storages(ep_priv);

    if (free_list_inited == true)
            __fr_freelist_destroy(ep_priv);

    if (ep_priv->cm_nic != NULL)
            ret = _gnix_cm_nic_free(ep_priv->cm_nic);

    if (ep_priv->nic != NULL)
            ret = _gnix_nic_free(ep_priv->nic);

    free(ep_priv);
    return ret;
```

The log message for _gnix_xpmem_handle_destroy is also incorrect, since the return value from that call is not saved.

### PR DESCRIPTION
**Pull request by sungeunchoi**
Signed-off-by: Sung-Eun Choi sungeunchoi@users.noreply.github.com

Fixes #952 

@sdvormwa

### CODE REVIEW

File: prov/gni/src/gnix_ep.c [hunk 1]
```diff
@@ -2063,26 +2063,44 @@ DIRECT_FN int gnix_ep_open(struct fid_domain *domain, struct fi_info *info,
 	*ep = &ep_priv->ep_fid;
 	return ret;
 
+	int err_ret;
```
Comment (sdvormwa) [inline prov/gni/src/gnix_ep.c]: Shouldn't this declaration be at the start of the function per the style guidelines?

Comment (sungeunchoi) [reply prov/gni/src/gnix_ep.c]: Our style checker didn't flag it, and generally I prefer to have the declarations close to the use.

Comment (hppritcha) [reply prov/gni/src/gnix_ep.c]: please move to the start of the function
