### PR TITLE
prov/gni: suppress spurious kdreg notifier events

### LINKED ISSUE #918: Warning in __clear_notifier_events() when using XPMEM
```
libfabric:gni:mr:__clear_notifier_events():568<warn> _gnix_notifier_get_event returned error: Invalid argument
```

This shows up with fi_rdm_pingpong in the fabtests suite, but others have reported seeing similar warnings when using XPMEM.

### LINKED ISSUE #937: __clear_notifier_events warning in gnitest
#934 started causing multiple __clear_notifier_events warning for a number of gnitests in the rdm_fi_pdc suite:

```
libfabric:gni:mr:__clear_notifier_events():568<warn> _gnix_notifier_get_event returned error: Invalid argument
```

@hppritcha

### PR DESCRIPTION
**Pull request by hppritcha**
The xpmem reg cache doesn't need to use kdreg.
This was confusing the wrapper code around kdreg.

Fixes #937
Fixes #918 

@sungeunchoi 
Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

File: prov/gni/src/gnix_mr_cache.c [hunk 1]
```diff
@@ -445,6 +445,10 @@ __clear_notifier_events(gnix_mr_cache_t *cache)
 		return;
 	}
 
+	if (!cache->attr.notifier) {
```
Comment (sungeunchoi) [inline prov/gni/src/gnix_mr_cache.c]: I'd check this before lazy dereg for now.  I say _for now_, because it's possible that the lazy dereg check will go away or be refactored.

File: prov/gni/src/gnix_xpmem.c [hunk 2]
```diff
@@ -70,6 +70,9 @@ struct gnix_xpmem_ht_entry {
 
 /*
  * TODO: should be adjustable from domain params
+ * Not notifier is set to NULL since xpmem device driver
```
Comment (sungeunchoi) [inline prov/gni/src/gnix_xpmem.c]: "Not"?  Did you mean "Note"?
