### PR TITLE
prov/gni: Fix use of FI_REMOTE_CQ_DATA.

### LINKED ISSUE #1190: Prevent use of FI_REMOTE_CQ_DATA when FI_RMA_EVENT is not set

### PR DESCRIPTION
**Pull request by e-harvey**
- Ensure that FI_REMOTE_CQ_DATA is only used when
FI_RMA_EVENT is also set.

- Added macro to check the previous condition.

- Updated rma source and unit tests to reflect these
changes.

- Updated VC struct doxy comment.

Note: I'm not sure we should be ORing in the FI_RMA_EVENT
flag in the changes I made for gnix_ep.c and the rdm* unit
tests. Also, the macro names might need some work.

Fixes #1190 and #1240.

Signed-off-by: Evan Harvey <eharvey@lanl.gov>

### CODE REVIEW

File: prov/gni/include/gnix_vc.h [hunk 1]
```diff
@@ -118,6 +118,8 @@ enum gnix_vc_conn_req_type {
  * @var flags                Bitmap used to hold vc schedule state
  * @var peer_irq_mem_hndl    peer GNI memhndl used for delivering
  *                           GNI_PostCqWrite requests to remote peer
+ * @var peer_apid            TODO
```
Comment (hppritcha) [inline prov/gni/include/gnix_vc.h]: i'll fill this TODO later.  this is for the xpmem protocol

File: prov/gni/include/gnix_util.h [hunk 2]
```diff
@@ -272,6 +273,15 @@ struct gnix_reference {
 #define _gnix_ref_get(ptr) __ref_get(ptr, ref_cnt)
 #define _gnix_ref_put(ptr) __ref_put(ptr, ref_cnt)
 
+/**
+ * Only allow FI_REMOTE_CQ_DATA when FI_RMA_EVENT is also set.
+ *
+ * @return zero if FI_REMOTE_CQ_DATA is not permitted; otherwise one.
+ */
+#define _gnix_assert_fi_remote_cq_data(_flags) (((_flags) & FI_REMOTE_CQ_DATA) \
```
Comment (chuckfossen) [inline prov/gni/include/gnix_util.h]: This macro doesn't assert. Please use a name more appropriate name. Maybe GNIX_FLAGS_REMOTE_CQ_DATA.

**Review by chuckfossen — DISMISSED** [review]
I just have one comment. Otherwise, looks ok

File: prov/gni/include/gnix_util.h (hunk 2 above)
Comment (e-harvey) [reply prov/gni/include/gnix_util.h]: What about `_gnix_allow_fi_remote_cq_data`?

Comment (chuckfossen) [reply prov/gni/include/gnix_util.h]: Yes, that's ok with me

**Comment by e-harvey** [comment]
Update copyright headers.

File: prov/gni/include/gnix_util.h [hunk 3]
```diff
@@ -272,6 +273,15 @@ struct gnix_reference {
 #define _gnix_ref_get(ptr) __ref_get(ptr, ref_cnt)
 #define _gnix_ref_put(ptr) __ref_put(ptr, ref_cnt)
 
+/**
+ * Only allow FI_REMOTE_CQ_DATA when FI_RMA_EVENT is also set.
+ *
+ * @return zero if FI_REMOTE_CQ_DATA is not permitted; otherwise one.
+ */
+#define _gnix_allow_fi_remote_cq_data(_flags) (((_flags) & FI_REMOTE_CQ_DATA) \
```
Comment (jswaro) [inline prov/gni/include/gnix_util.h]: Macros should be fully capitalized unless there is a good reason for it otherwise. That's how we distinguish macro from function at a glance.

File: prov/gni/include/gnix_vc.h (hunk 1 above)
Comment (jswaro) [reply prov/gni/include/gnix_vc.h]: If this is for the xpmem work, should it be part of this PR?

File: prov/gni/include/gnix_util.h (hunk 3 above)
Comment (e-harvey) [reply prov/gni/include/gnix_util.h]: Both chuck and I are good with this name. Do you still want me to capatilize?

Comment (jswaro) [reply prov/gni/include/gnix_util.h]: @chuckfossen Preferences on capitalization for macros?

Comment (e-harvey) [reply prov/gni/include/gnix_util.h]: @jswaro @chuckfossen No need to discuss further, i'll just refactor this.

File: prov/gni/src/gnix_rma.c [hunk 4]
```diff
@@ -250,7 +250,7 @@ int __smsg_rma_data(void *data, void *msg)
 	struct gnix_fid_ep *ep = vc->ep;
 	gni_return_t status;
 
-	if (hdr->flags & FI_REMOTE_CQ_DATA && ep->recv_cq) {
+	if (_GNIX_ALLOW_FI_REMOTE_CQ_DATA(hdr->flags) && ep->recv_cq) {
```
Comment (chuckfossen) [inline prov/gni/src/gnix_rma.c]: The leading underscore is only really needed for function names. Macros don't need them. I know we're being picky but I don't think any of our macros have leading underscores. Let's remove it.

**Comment by e-harvey** [comment]
It looks like the reference from ztiffany was not intended - it appears to be from an old commit by Sean Hefty.

**Comment by e-harvey** [comment]
I'll wait until #1207 is merged in to update this PR.

File: prov/gni/test/common.h [hunk 5]
```diff
@@ -53,4 +54,9 @@ void calculate_time_difference(struct timeval *start, struct timeval *end,
 		int *secs_out, int *usec_out);
 int dump_cq_error(struct fid_cq *cq, void *context, uint64_t flags);
 
+static inline struct gnix_fid_ep *get_gnix_ep(struct fid_ep *fid_ep)
```
Comment (jswaro) [inline prov/gni/test/common.h:56]: Why isn't this just a define/macro?

**Review by jswaro — APPROVED** [review]
Conditionally approved based on the other reviewers feedback. There isn't anything here that I don't think we couldn't fix easily later if need be.

**Comment by jswaro** [comment]
You need to rebase and address conflicts.

**Comment by jswaro** [comment]
Please squash before merge.

File: prov/gni/test/common.h (hunk 5 above)
Comment (sungeunchoi) [reply prov/gni/test/common.h:56]: Leave it.  Let's use language constructs over the preprocessor whenever possible.

**Comment by a-abraham** [comment]
@e-harvey -  It looks like you've disabled the functionality you added when the fi_more flag is present. In that case, do you still need to wait for #1207 ?

**Comment by e-harvey** [comment]
> @e-harvey - It looks like you've disabled the functionality you added when the fi_more flag is present.

I'm not sure I understand, could you elaborate? 

> In that case, do you still need to wait for #1207 ?

Yes, I want to wait for #1207 to be merged so I can rebase this PR and replace the new references to FI_REMOTE_CQ_DATA to GNIX_ALLOW_FI_REMOTE_CQ_DATA.

**Comment by a-abraham** [comment]
Sorry, I phrased that poorly.  I'm just referring to the additional checks that you made in rdm_rma_check_tcqe. You ensured that they shouldn't be executed when fi_more is set. So in that regard things look good to me.

If all you need from #1207  is to rename the references to GNIX_ALLOW_FI_REMOTE_CQ_DATA - I can take care of that after your PR. I still need to add a Test case to #1207, and may not get around to it for a few days yet.

**Comment by e-harvey** [comment]
> Sorry, I phrased that poorly. I'm just referring to the additional checks that you made in rdm_rma_check_tcqe. You ensured that they shouldn't be executed when fi_more is set. So in that regard things look good to me.

No worries. Thanks for reviewing these changes.

> If all you need from #1207 is to rename the references to GNIX_ALLOW_FI_REMOTE_CQ_DATA - I can take care of that after your PR. I still need to add a Test case to #1207, and may not get around to it for a few days yet.

Okay, I'll check with my reviewers and then merge if they are good with these changes.

**Comment by e-harvey** [comment]
@chuckfossen, @sungeunchoi, @a-abraham: Do you have any more feedback before I merge these changes?

**Review by a-abraham — APPROVED** [review]

File: prov/gni/test/api.c [hunk 6]
```diff
@@ -297,16 +300,18 @@ int rdm_api_check_data(char *buf1, char *buf2, int len)
 
 void rdm_api_check_cqe(struct fi_cq_tagged_entry *cqe, void *ctx,
 		      uint64_t flags, void *addr, size_t len,
-		      uint64_t data)
+		      uint64_t data, struct fid_ep *fid_ep)
```
Comment (sungeunchoi) [inline prov/gni/test/api.c:303]: Why are we maintaining this function if it's not used?  In fact, all the rdm_api_check_* functions are not used and should be removed.

@chuckfossen Is there a reason to keep them around?

File: prov/gni/test/rdm_atomic.c [hunk 7]
```diff
@@ -481,7 +484,7 @@ void do_min(int len)
 
 	cr_assert_eq(ret, 1, "fi_cq_read returned %d %d", ret,
 			dump_cq_error(send_cq[0], target, 0));
-	rdm_atomic_check_tcqe(&cqe, target, FI_ATOMIC | FI_WRITE, 0);
+	rdm_atomic_check_tcqe(&cqe, target, FI_ATOMIC | FI_WRITE, 0, ep[1]);
```
Comment (sungeunchoi) [inline prov/gni/test/rdm_atomic.c]: This check makes no sense.  You are checking the data field on the initiating (send) side.  In order to test for the remote cq data, you need to request for remote CQ events on ep[1] and look at the events delivered there.  This is true of all the checks you added in this file.

Comment (e-harvey) [reply prov/gni/test/rdm_atomic.c]: Ok. Do we want to change these tests to report completions on the remote peer and read those completions or simply pass ep[0] into this test and others like it?

File: prov/gni/test/rdm_dgram_rma.c [hunk 8]
```diff
@@ -776,7 +792,7 @@ void do_write(int len)
 		return;
 	}
 	cr_assert_eq(ret, 1);
-	rdm_rma_check_tcqe(&cqe, target, FI_RMA | FI_WRITE, 0);
+	rdm_rma_check_tcqe(&cqe, target, FI_RMA | FI_WRITE, 0, ep[1]);
```
Comment (sungeunchoi) [inline prov/gni/test/rdm_dgram_rma.c]: This is the same as above.  Need to check the remote CQ.

Comment (sungeunchoi) [reply prov/gni/test/rdm_dgram_rma.c]: As are many of the rest of these in this file.

File: prov/gni/test/rdm_dgram_stx.c [hunk 9]
```diff
@@ -1216,7 +1223,7 @@ static void do_writedata(int len)
 
 	rdm_rma_check_tcqe(&dcqe, NULL,
```
Comment (sungeunchoi) [inline prov/gni/test/rdm_dgram_stx.c:1225]: This one is okay.

File: prov/gni/test/rdm_atomic.c (hunk 7 above)
Comment (sungeunchoi) [reply prov/gni/test/rdm_atomic.c]: We don't test this code path in many places, so I think at least some of them should change to get a remote event.

The RMA tests are set up for it (in fact, some of them check already), so I'd add it to those and skip the atomic tests for now.  You can add an issue to add remote CQ event checking for the atomic tests.

**Review by sungeunchoi — CHANGES_REQUESTED** [review]
Update RMA test to check for remote CQ data.

File: prov/gni/test/rdm_atomic.c (hunk 7 above)
Comment (sungeunchoi) [reply prov/gni/test/rdm_atomic.c]: In thinking about this a little more, I think we need to test both paths, with and without RMA events.  In reviewing the tests, if there is an obvious way to test both, let's do that.  It might just be a matter of factoring the set up function.

Comment (e-harvey) [reply prov/gni/test/rdm_atomic.c]: I agree that both paths should be tested. One option for testing both paths would be to add new test suites for each existing test suite that sets FI_RMA_EVENT. Then, in each of the existing do functions, of which there are 52, we would need to check for fi rma event and poll the recv CQ if it's set. This last part could be encapsulated in a function. Add new test suites would also not be hard. I will update these tests unless there are objections.

File: prov/gni/test/api.c (hunk 6 above)
Comment (chuckfossen) [reply prov/gni/test/api.c:303]: They can be removed.

Comment (e-harvey) [reply prov/gni/test/api.c:303]: Opening an issue.

File: prov/gni/test/rdm_atomic.c (hunk 7 above)
Comment (e-harvey) [reply prov/gni/test/rdm_atomic.c]: Actually, looking more closely in the GNI provider, completion events are not generated on the remote peer for atomic operations, only counters are used. I can't tell from the man page, is this intended? If so, we can simply reset rdm_atomic.c. Sorry for the confusion and thank you for catching this mistake.

**Comment by e-harvey** [comment]
the LANL CI is failing with:
```
cc1: all warnings being treated as errors
make: *** [prov/gni/test/prov_gni_test_gnitest-av.o] Error 1
make: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
make: *** [prov/gni/test/prov_gni_test_gnitest-bitmap.o] Error 1
```

Is this related to the Criterion update?

**Comment by e-harvey** [comment]
bot:lanl:retest

**Comment by e-harvey** [comment]
We need #1276 merged and to rebase on top of master before the LANL CI will pass.

**Comment by sungeunchoi** [comment]
I don't like the check cqe functions, but in the interest of time, let's do the following.

- Keep the code as is but add a short comment in all the check cqe functions that were modified to take eps.  The comment should say that we should change this to only check for remote CQ data if the flags passed in include FI_RMA_EVENT.  That is, get rid of GNIX_ALLOW_FI_REMOTE_CQ_DATA, first look at the flags, then check the ep.

- Add an issue for the above described change, which includes passing in NULL for the cases when FI_RMA_EVENT is not set.

**Review by sungeunchoi — CHANGES_REQUESTED** [review]
No code changes.

**Review by sungeunchoi — APPROVED** [review]
