### PR TITLE
prov/gni: fix getinfo return code

### LINKED ISSUE #51: gni provider getinfo method not returning correct error code
Turns out that a provider that is not available should return -FI_ENODATA in its getinfo method.  Any other error return value will result in fi_getinfo method returning early with querying other providers for their availability.  This behavior of the gni provider is evident when running some of the fabtests/simple on the front end nodes of a Cray system using any ip addr other than the one assiged to ipogif0.

### PR DESCRIPTION
**Pull request by hppritcha**
Turns out the way the upper level fi_getinfo is
implemented, a provider that isn't available for
a given input address, etc. must return FI_ENODATA.
Otherwise, the fi_getinfo will return early and not
probe other potential providers.

@bturrubiates 

Fixes #51

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

File: prov/gni/src/gnix_fabric.c [hunk 1]
```diff
@@ -348,7 +348,13 @@ static int gnix_getinfo(uint32_t version, const char *node, const char *service,
 		if (gnix_info->fabric_attr) free(gnix_info->fabric_attr);
```
Comment (bturrubiates) [inline prov/gni/src/gnix_fabric.c:348]: Looks good, but as a sidenote you don't need to have branches around all of those. You can just do something like:

```
err:
    if (gnix_info) {
        free(gnix_info->tx_attr);
        free(gnix_info->rx_attr);
        free(gnix_info->ep_attr);
        free(gnix_info->domain_attr);
        free(gnix_info->fabric_attr);
        free(gnix_info);
    }

    /*
     *  for the getinfo method, we need to return -FI_ENODATA  otherwise
     *  the fi_getinfo call will make an early exit without querying
     *  other providers which may be avaialble.
     */
    return -FI_ENODATA;
```

**Comment by bturrubiates** [comment]
@hppritcha, going to merge.
