### PR TITLE
prov/gni: fix race condition with pending_vcs list

### LINKED ISSUE #369: vc_management::vc_conn_accept test fails during teardown

### PR DESCRIPTION
**Pull request by hppritcha**
There was a problem revealed by the vc_management/vc_accept.
To fix the problem, the pending_vcs list on the nic had to
be switched to a dlist.  During the _gnix_vc_destroy call
a check is now made to see if the vc is in the pending_vcs
list and if so is removed.

Fixes #369

Checked with fabtests and criterion.  Ran criterion numerous times and
did not see the teardown failure.

@ztiffany @sungeunchoi 

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by sungeunchoi** [comment]
:+1:

File: prov/gni/src/gnix_vc.c [hunk 1]
```diff
@@ -908,6 +908,18 @@ int _gnix_vc_destroy(struct gnix_vc *vc)
...
 
 	/*
+	 * if the vc is in a nic's work queue, remove it
+	 */
+
+	if (_gnix_test_and_clear_bit(&vc->flags, GNIX_VC_FLAG_SCHEDULED)) {
+		fastlock_acquire(&nic->pending_vc_lock);
+		dlist_remove(&vc->pending_list);
+		fastlock_release(&nic->pending_vc_lock);
+		GNIX_INFO(FI_LOG_EP_CTRL, "Scheduled VC (%p)\n", vc);
```
Comment (ztiffany) [inline prov/gni/src/gnix_vc.c]: "Scheduled VC" is not correct.  Change to "Unscheduled"?

**Comment by ztiffany** [comment]
:+1:

File: prov/gni/src/gnix_vc.c (hunk 1 above)
Comment (hppritcha) [inline prov/gni/src/gnix_vc.c]: fixed in fresh commit
