### PR TITLE
prov/gni: Fix FI_NOTIFY_FLAGS_ONLY bug.

### LINKED ISSUE #1245: Fix FI_NOTIFY_FLAGS_ONLY bug
The current implementation to support `FI_NOTIFY_FLAGS_ONLY` checks an EP's `op_flags` field for the `FI_NOTIFY_FLAGS_ONLY` mode bit but this mode bit will never be set in an ep's `op_flags`.

related to #1231

### PR DESCRIPTION
**Pull request by e-harvey**
- _gnix_cq_add_event now checks the ep's mode bit and
    masks off the flags if the FI_NOTIFY_FLAGS_ONLY bit is set.
    
- Ensured mode bit is propagated to internal info struct.
    
- Update the unit tests to reflect these changes.

Fixed #1245

### CODE REVIEW

**Comment by jswaro** [comment]
Write some unit tests to make sure it works as expected. I'd have expected any existing tests to have failed if this was originally working.

**Comment by e-harvey** [comment]
Unit tests have been written in cq.c already. It's actually my implementation introduced in #1183 that is incorrect. I'm fixing it now.

**Comment by jswaro** [comment]
It shouldn't be tested by manually modifying the EPs flags. Write a different setup routine to test this in a more application-friendly approach.

**Comment by e-harvey** [comment]
Sounds good, thanks for the tips Jim!

**Comment by sungeunchoi** [comment]
Is there an open issue about this problem?

File: prov/gni/test/cq.c [hunk 1]
```diff
@@ -852,58 +852,43 @@ Test(cq_wait_set, fd, .init = setup, .disabled = true)
...
-			break;
-		case (FI_RMA_EVENT | FI_NOTIFY_FLAGS_ONLY):
-			expected_flags &= (FI_REMOTE_READ | FI_REMOTE_WRITE |
-					   FI_RMA | FI_REMOTE_CQ_DATA |
-					   FI_MULTI_RECV);
-			break;
-		default:
-			cr_assert(0, "invalid op flags");
+	switch (flags & FI_RMA_EVENT) {
+	case ~FI_RMA_EVENT:
```
Comment (chuckfossen) [inline prov/gni/test/cq.c]: This won't work, Evan. ~FI_RMA_EVENT is not 0. Just simplify this to an if/else statement.

File: prov/gni/test/cq.c [hunk 2]
```diff
@@ -852,58 +852,43 @@ Test(cq_wait_set, fd, .init = setup, .disabled = true)
...
+	do_cq_notify(FI_REMOTE_READ | FI_REMOTE_WRITE |
+		     FI_RMA | FI_REMOTE_CQ_DATA |
+		     FI_MULTI_RECV | FI_RMA_EVENT);
 }
 
-Test(cq_notify_flags, notify_set_and_rma_event_set)
+Test(cq_notify_flags, not_fi_rma_event)
 {
-	do_cq_notify(FI_NOTIFY_FLAGS_ONLY | FI_RMA_EVENT);
+	do_cq_notify(~FI_RMA_EVENT);
```
Comment (chuckfossen) [inline prov/gni/test/cq.c:891]: Correct me if I'm wrong, but this should be 0, not ~FI_RMA_EVENT.

**Review by chuckfossen — CHANGES_REQUESTED** [review]

File: prov/gni/test/cq.c (hunk 1 above)
Comment (e-harvey) [reply prov/gni/test/cq.c]: Thanks for catching this.

File: prov/gni/test/cq.c (hunk 2 above)
Comment (e-harvey) [reply prov/gni/test/cq.c:891]: It should be ~FI_RMA_EVENT but do_cq_notify was incorrect.

**Comment by e-harvey** [comment]
Note: I won't have access until Friday to run gnitest & cray-tests on this PR.

File: prov/gni/test/cq.c (hunk 2 above)
Comment (chuckfossen) [reply prov/gni/test/cq.c:891]: Have you tested using ~FI_RMA_EVENT? ~FI_RMA_EVENT would give you 0xFEFFFFFFFFFFFFFF which is not what you want since do_cq_notify passes it to a switch statement so you'll get the default.

Comment (e-harvey) [reply prov/gni/test/cq.c:891]: Yes, I changed the switch to an `if (flags & FI_RMA_EVENT) {...} else {...}` per your suggestion - thank you for catching this.

There's only two cases when FI_NOTIFY_FLAGS_ONLY mode bit if being tested: ~FI_RMA_EVENT and ~0.

Anyways, some of the dgram_rma tests are failing with `CQE flags mismatch` right now.

Comment (chuckfossen) [reply prov/gni/test/cq.c:891]: In general, using a ~BITFLAG isn't what you want since it does more than clear the flag you want. Just using 0 would suffice in this case.

Comment (e-harvey) [reply prov/gni/test/cq.c:891]: That makes sense, the reason i'm using ~FI_RMA_EVENT and not 0 is because I want to make sure all the correct flags get masked off in _gnix_cq_add_event.

**Comment by e-harvey** [comment]
@jswaro, @chuckfossen: 5f9951e is passing gnitest and cray-tests. Please let me know if you have any feedback or want me to squash and merge.

**Comment by sungeunchoi** [comment]
Why are you created an uninitialized variable called mode_bits in all the tests, and then only using it to initialize the hints field?

**Comment by e-harvey** [comment]
> Why are you created an uninitialized variable called mode_bits in all the tests, and then only using it to initialize the hints field?

The majority of the unit tests set mode to ~0 before I made this 'mode_bits' change.

Setting mode to ~0 would enable FI_NOTIFY_FLAGS_ONLY and change the flags reported by all CQEs causing the majority of the unit tests to fail. To fix this, and set FI_NOTIFY_FLAGS_ONLY for the new unit tests in cq.c I added the static variable `mode_bits` (initialized to 0 by default). 

I thought the `mode_bits` field would be useful going forward. However, I can just add a new initialization function for the new unit tests in cq.c and change all the existing mode initializations from ~0 to 0; is the preferred?

**Comment by sungeunchoi** [comment]
Given your explanation, shouldn't the mode_bits variable be set to `~FI_NOTIFY_FLAGS_ONLY` to be testing the exact same behavior prior to the change?

**Comment by e-harvey** [comment]
> Given your explanation, shouldn't the mode_bits variable be set to ~FI_NOTIFY_FLAGS_ONLY to be testing the exact same behavior prior to the change?

Yes.

**Comment by sungeunchoi** [comment]
For existing tests, let's use ~FI_NOTIFY_FLAGS_ONLY.  But for future tests, I think that we should use ~0.  So please put a comment at the declaration/initialization of mode_bits in each file to say that we are setting it to ~FI_NOTIFY_FLAGS_ONLY because the tests were written before FI_NOTIFY_FLAGS_ONLY was supported in 1.5, but that going forward we should be using ~0.

We can consider changing the tests to use ~0 in the future.

**Comment by e-harvey** [comment]
> For existing tests, let's use ~FI_NOTIFY_FLAGS_ONLY. But for future tests, I think that we should use ~0. So please put a comment at the declaration/initialization of mode_bits in each file to say that we are setting it to ~FI_NOTIFY_FLAGS_ONLY because the tests were written before FI_NOTIFY_FLAGS_ONLY was supported in 1.5, but that going forward we should be using ~0.
> 
> We can consider changing the tests to use ~0 in the future.

Ok, thank you for the feedback.

**Comment by jswaro** [comment]
> For existing tests, let's use ~FI_NOTIFY_FLAGS_ONLY. But for future tests, I think that we should use ~0. So please put a comment at the declaration/initialization of mode_bits in each file to say that we are setting it to ~FI_NOTIFY_FLAGS_ONLY because the tests were written before FI_NOTIFY_FLAGS_ONLY was supported in 1.5, but that going forward we should be using ~0.
> 
> We can consider changing the tests to use ~0 in the future. 

I think our testing would be well served from using well-defined mode bits, not ~0. I'd rather know prior to testing that we are requesting a very specific bitset. As new functionality is added, we might end up enabling things we hadn't intended to, and then the tests need to be modified because we enabled a bunch of other functionality when we only intended to eliminate the one bit.  

I'd prefer the following logic:

```C
#define GNIX_DEFAULT_MODE_BITS (some_bit_set_here)

#define ENABLE_BIT(bit, var) \
    do { \ 
        var |= (bit); \
    } while (0)

#define DISABLE_BIT(bit, var) \
    do { \
        var &= ~(bit); \
    } while (0) 

static inline int some_suite_setup_function()
{
      info->mode_bits = GNIX_DEFAULT_MODE_BITS;
}

static inline int some_other_suite_setup_function()
{  
     info->mode_bits = GNIX_DEFAULT_MODE_BITS;

     ENABLE_BIT(BIT_TO_TEST, info->mode_bits);
}

```

**Comment by e-harvey** [comment]
Those macros seem like a very good addition to me. We could add them to common.h. However, what should the default bitset be, 0?

**Comment by jswaro** [comment]
> Those macros seem like a very good addition to me. We could add them to common.h. However, what should the default bitset be, 0?

I think that question should be directed at the author of the tests, whomever that might be. In general, I'd recommend a minimal bit-set.

**Comment by e-harvey** [comment]
> I think that question should be directed at the author of the tests, whomever that might be. In general, I'd recommend a minimal bit-set.

Ok, I'll open an issue for this addition.

File: prov/gni/src/gnix_cq.c [hunk 3]
```diff
@@ -289,16 +289,14 @@ ssize_t _gnix_cq_add_event(struct gnix_fid_cq *cq, struct gnix_fid_ep *ep,
 {
 	struct gnix_cq_entry *event;
 	struct slist_entry *item;
-	uint64_t op_flags, mask;
+	uint64_t mask;
 
-	/* TODO: Move below conditional to gnix_cq.h and make static/inline */
+	/* TODO: handle scalable eps - note info is NULL for scalable eps */
```
Comment (jswaro) [inline prov/gni/src/gnix_cq.c]: TODO still present.

**Review by jswaro — APPROVED** [review]
Conditionally approved based on feedback from other reviewers. There is nothing here that we couldn't easily fix later if need be.

**Comment by jswaro** [comment]
You need to rebase and resolve conflicts. Squash before merge.

File: prov/gni/src/gnix_ep.c [hunk 4]
```diff
@@ -2326,6 +2326,7 @@ int _gnix_ep_alloc(struct fid_domain *domain, struct fi_info *info,
 	ep_priv->ep_fid.ops = &gnix_ep_ops;
 	ep_priv->domain = domain_priv;
 	ep_priv->type = info->ep_attr->type;
+	ep_priv->info = fi_dupinfo(info);
```
Comment (chuckfossen) [inline prov/gni/src/gnix_ep.c:2329]: make sure there is a corresponding fi_freeinfo() call on destruct.

Comment (chuckfossen) [reply prov/gni/src/gnix_ep.c:2329]: or, does that already happen in __ep_destruct?

Comment (e-harvey) [reply prov/gni/src/gnix_ep.c:2329]: yea, it looks like once the reference count hits zero __ep_destruct will free it.

**Review by chuckfossen — APPROVED** [review]
