### PR TITLE
prov/gni: use br0 iface for nodes with KNC

### LINKED ISSUE #706: gnixu_get_pe_from_ip fails for nodes with Xeon Phis
Hi,

I am using libfabric on a Cray with Xeon Phis and gnixu_get_pe_from_ip fails. I am not trying to run libfabric on the Phis. The problem is on the host cpu.

On the host, the IP address is assigned to ipogif0 and br0.  When gnixu_get_pe_from_ip scans /proc/net/arp for the ip address, it also checks whether line contains "ipogif". That last part fails. Here is an example line from /proc/net/arp:

`10.128.0.2       0x1         0x6         00:01:01:00:00:01     *        br0`

### PR DESCRIPTION
**Pull request by hppritcha**
On XC nodes with KNC, the "bridge" name for the
gni device shows up in the arp tables.  Check both
ipogif0 and fall back to br0 to get the local
ipv4 addr.

Thanks to @tschuett for reporting.
fixes ofi-cray/libfabric-cray#706

@e-harvey 
@ztiffany 

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by e-harvey** [comment]
:+1:

File: prov/gni/src/gnix_nameserver.c [hunk 1]
```diff
@@ -186,37 +221,27 @@ int gnix_resolve_name(IN const char *node, IN const char *service,
...
+	 * Get the address for the ipogif0 interface
+	 * On nodes with KNC accelerators, the iface is br0
+	 */
 
-	ret = ioctl(sock, SIOCGIFADDR, &ifr);
-	if (ret == -1) {
+	ret =  __gnix_ipaddr_from_iface("ipogif0", &sin);
+	if (ret != FI_SUCCESS)
+		ret =  __gnix_ipaddr_from_iface("br0", &sin);
+	if (ret != FI_SUCCESS) {
```
Comment (ztiffany) [inline prov/gni/src/gnix_nameserver.c]: Need to indent error handling code from second __gnix_ipaddr_from_iface() call.
