### PR TITLE
prov/gni: fix an issue with datagram exchange

### LINKED ISSUE #599: locking/race condition with datagram thread
There appears to be a race condition, or lock usage problem with the VC connection code when using `control_progress = FI_PROGRESS_AUTO`.  The Open MPI by default uses `FI_PROGRESS_MANUAL` while the mpich uses `FI_PROGRESS_AUTO`, so the problem isn't observed with out-of-the-box Open MPI.

### PR DESCRIPTION
**Pull request by hppritcha**
Turns out there was a difficult to hit edge case where
a vc could end up sending a datagram both for connect
request and connect request response(ack), resulting in
an error in connection setup at the target.

The problem was insufficient checking in the ack
progress function.  It needs to check whether or not
the vc has either already moved to connected state or
a GNI datagram for this vc setup has already been posted.

Add some additional GNIX_WARN's for various edge cases.
The warning statements helped in debugging this problem.

Fixes #599 

@ztiffany 
@sungeunchoi 

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

File: prov/gni/src/gnix_vc.c [hunk 1]
```diff
@@ -892,10 +894,13 @@ static int __gnix_vc_conn_ack_prog_fn(void *data, int *complete_ptr)
 	fastlock_acquire(&ep->vc_ht_lock);
 
 	/*
-	 * we may have already been moved to connecting or
-	 * connected, if so early exit.
+	 * we may have already been moved to connected or
+	 * the datagram for a earlier conn request for this
+	 * vc we are done.  The connection will be completed
```
Comment (sungeunchoi) [inline prov/gni/src/gnix_vc.c]: I having trouble parsing this first sentence (especially the "we are done" part).

File: prov/gni/src/gnix_vc.c [hunk 2]
```diff
@@ -599,6 +600,7 @@ static int __gnix_vc_hndl_conn_resp(struct gnix_cm_nic *cm_nic,
 	 */
 
 	vc->conn_state = GNIX_VC_CONNECTED;
+	vc->peer_id = peer_id;
```
Comment (sungeunchoi) [inline prov/gni/src/gnix_vc.c:606]: What did this line fix?  Seems important.

**Comment by ztiffany** [comment]
Looks good once the questions are answered.

File: prov/gni/src/gnix_vc.c (hunk 2 above)
Comment (hppritcha) [inline prov/gni/src/gnix_vc.c:606]: i added that line to help with debugging.  its not really used, although I see I was thinking of using it in `_gnix_rma_post_irq` at some point.

Comment (hppritcha) [inline prov/gni/src/gnix_vc.c:606]: There's another path where it would be worth setting the peer_id.  I'll add that to this PR.

File: prov/gni/src/gnix_vc.c (hunk 1 above)
Comment (hppritcha) [inline prov/gni/src/gnix_vc.c]: okay I'll fix this up.

**Comment by hppritcha** [comment]
@sungeunchoi could you recheck wording?

File: prov/gni/src/gnix_vc.c [hunk 3]
```diff
@@ -892,10 +898,14 @@ static int __gnix_vc_conn_ack_prog_fn(void *data, int *complete_ptr)
 	fastlock_acquire(&ep->vc_ht_lock);
 
 	/*
-	 * we may have already been moved to connecting or
-	 * connected, if so early exit.
+	 * we may have already been moved to connected or
+	 * the datagram from an earlier conn request for this
+	 * vc was posted to GNI datagram state machine.  The
+	 * connection will be completed in the __gnix_vc_hndl_conn_resp
+	 * datagram callback in the later case.
```
Comment (sungeunchoi) [inline prov/gni/src/gnix_vc.c]: Now that makes sense to me.  But one last nit: later -> latter.
