### PR TITLE
prov/gni: Refactor GNI provider FI_MULTI_RECV

### LINKED ISSUE #1003: need to handle generation of CQEs for FI_MULTI_RECV recvs better
The current way `FI_MULTI_RECV` technically does work, but the out-of-order generation of completion events may be confusing to an application writer.  Unlike networks that deliver puts/send messages in order, the GNI provider doesn't try to complete and report receives in order.  Note the matching portion of the receive is done in order, its just the bulk data may be fetched out of order.

We should probably go with the option described in the fi_cq man page where we generate a special CQE when the buffer has been filled and the request is being freed.  That will ensure that the application only gets notification that the FI_MULTI_RECV buffer can be reused once all message data has been received.

### LINKED ISSUE #1116: Matching to FI_ADDR_UNSPEC does not work with FI_MULTI_RECV
The first message to arrive overwrites the endpoint addr field in the gnix_fab_req, and then we don't match to subsequent sends from other endpoints.

### PR DESCRIPTION
**Pull request by hppritcha**
The GNI provider implementation of FI_MULTI_RECV had to
be refactored to fix numerous issues with the original implementation.

With this refactor, the provider now handles the case where
messages can be received into a FI_MULTI_RECV buffer from numerous
different EPs.

With this refactor, receives of messages using the provider's
rendezvous protocol now function correctly.  Previously an application
would not be correctly notified when all messages had been transfered
into the buffer in the case that some transfers used the rendezvous
protocol.

In order to correctly notify the application when the buffer has
been released, a separate FI_MULTI_RECV CQ event is now generated
without the FI_RECV flag set.  See description of FI_MULTI_RECV
CQs in the fi_cq man page.

Fixes ofi-cray/libfabric-cray#1003
Fixes ofi-cray/libfabric-cray#1116

This PR does not address a truncated message reporting issue.
That will be handled as a separate PR as its not directly related to
problems with the original FI_MULTI_RECV implementation.

Relates to ofi-cray/libfabric-cray#1119

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

File: prov/gni/include/gnix.h [hunk 1]
```diff
@@ -1026,9 +1034,9 @@ struct gnix_fab_req {
 
 	/* common to rma/amo/msg */
 	union {
-		struct gnix_fab_req_rma rma;
-		struct gnix_fab_req_msg msg;
-		struct gnix_fab_req_amo amo;
+		struct gnix_fab_req_rma   rma;
```
Comment (jshimek) [inline prov/gni/include/gnix.h:1037]: Not to nitpick but is this fixing a spacing issue or is it unneccessary?

File: prov/gni/src/gnix_msg.c [hunk 2]
```diff
@@ -1904,31 +1952,15 @@ static int __smsg_eager_msg_w_data(void *data, void *msg)
...
-			GNIX_DEBUG(FI_LOG_EP_DATA, "Freeing req: %p\n", req);
+		GNIX_DEBUG(FI_LOG_EP_DATA, "Freeing req: %p\n", req);
 
-			/* Dequeue and free the request. */
+		/* Dequeue and free the request. */
+		if (mrecv_req == NULL)
 			_gnix_remove_tag(posted_queue, req);
-			_gnix_fr_free(ep, req);
-		}
+		_gnix_fr_free(ep, req);
```
Comment (ztiffany) [inline prov/gni/src/gnix_msg.c]: It doesn't make sense to me that we would ever want to free the request after not removing in from the receive queue.

**Comment by hppritcha** [comment]
found a few issues that fixes that allows the fabtests ```FI_MULTI_RECV``` test to pass.

File: prov/gni/src/gnix_msg.c (hunk 2 above)
Comment (hppritcha) [reply prov/gni/src/gnix_msg.c]: i see the code is a little confusing.  I'll put both statements inside the 'if'.

File: prov/gni/include/gnix.h (hunk 1 above)
Comment (hppritcha) [reply prov/gni/include/gnix.h:1037]: i think this may be github diff.  format.  Not seeing it with vim.

**Comment by ztiffany** [comment]
1. Would it be possible to split the bug fixes?
2. What part of the fix solves the problem where we couldn't match sends from multiple peers to the same multi recv requests?
3. Could you have solved this while reusing most of the existing code?  It looks like we only needed a couple new fields in the request to help track the state of the multi-recv to know when to generate the final completion.

**Comment by hppritcha** [comment]
I'm not going to try to reuse the existing code.  This is a much simpler solution in my opinion.

**Comment by hppritcha** [comment]
This does fix the various problems that @sungeunchoi was seeing trying to use fi multi recv with more than two endpoints, the problem with out-of-order completion of messages when using the rendezvous protocol to fill the buffer, etc.

**Comment by sungeunchoi** [comment]
@hppritcha Can you answer Zach's question 1 & 2 above?
@ztiffany Can you explain why you think what's there is a reasonable option?

**Comment by hppritcha** [comment]
Okay, so I looked up examples of why @sungeunchoi 's tests did not work with more than on source EP:
In original code there were constructs like this:

```
¬       /* Lookup a matching posted request. */
¬       req = _gnix_match_tag(posted_queue, hdr->msg_tag, 0, FI_PEEK, NULL,
¬       ¬       ¬             &vc->peer_addr);
¬       if (req) {
¬       ¬       req->addr = vc->peer_addr;
¬       ¬       req->gnix_ep = ep;
¬       ¬       req->vc = vc;

```
The setting of  ```req->addr``` turns off a multi-receive requests ```FI_ADDR_UNSPEC```.  The fact that a new receive request wasn't being created for each match in posted queue is a problem.  That is now being done using the new approach where many regular receive requests can be associated with a single multi-receive request, each matched receive request being processed separately.

I don't see a way that makes sense in this case to split this PR into one that fixes the specific problem Sung was hitting while also not solving issue #1003.

**Comment by ztiffany** [comment]
I was thinking you could get around setting the req->addr field in an FI_MULTI_RECV request.  If the request is complete (ready to generate it's FI completion) there's no need to keep anything else around.

**Comment by hppritcha** [comment]
getting kind of gross don't you think?  I'm interested in a comprehensive fix to the several fi multi receive issues stemming from the initial design, not small workarounds.

File: prov/gni/include/gnix_ep.h [hunk 3]
```diff
@@ -245,6 +245,32 @@ _gnix_fr_alloc(struct gnix_fid_ep *ep)
...
+		fr = container_of(de, struct gnix_fab_req, dlist);
+		fr->gnix_ep = ep;
+		fr->cb = cb;
+		_gnix_ref_init(&fr->ref_cnt, 1, cb);
+		dlist_init(&fr->dlist);
+		dlist_init(&fr->msg.tle.free);
+	}
+
+	/* reset common fields */
+	fr->tx_failures = 0;
```
Comment (sungeunchoi) [inline prov/gni/include/gnix_ep.h]: If `ret != FI_SUCCESS` this will deference NULL.

File: prov/gni/include/gnix_ep.h [hunk 4]
```diff
@@ -245,6 +245,32 @@ _gnix_fr_alloc(struct gnix_fid_ep *ep)
...
+	_gnix_ref_get(ep);
```
Comment (sungeunchoi) [inline prov/gni/include/gnix_ep.h]: Do you want to take the ref if `fr == NULL`?

File: prov/gni/include/gnix.h [hunk 5]
```diff
@@ -750,6 +750,9 @@ struct gnix_fab_req_msg {
 	size_t                       send_iov_cnt;
 	uint64_t                     send_flags;
 	size_t			     cum_send_len;
+	struct gnix_fab_req 	 *parent;
+	size_t                   mr_space_left;
```
Comment (jswaro) [inline prov/gni/include/gnix.h]: Nit: Can you fix the indentation/spacing to match those of the neighboring fields?

File: prov/gni/include/gnix.h (hunk 1 above)
Comment (jswaro) [reply prov/gni/include/gnix.h:1037]: It shows in the diff as two added spaces. Whether it is extra spaces, or a tab, it seems to be an unintended change.

File: prov/gni/include/gnix_ep.h [hunk 6]
```diff
@@ -245,6 +245,32 @@ _gnix_fr_alloc(struct gnix_fid_ep *ep)
...
 
+static inline struct gnix_fab_req *
+_gnix_fr_alloc_w_cb(struct gnix_fid_ep *ep, void (*cb)(void *))
+{
+	struct dlist_entry *de = NULL;
+	struct gnix_fab_req *fr = NULL;
+	int ret = _gnix_fl_alloc(&de, &ep->fr_freelist);
+
+	while (unlikely(ret == -FI_EAGAIN))
+		ret = _gnix_fl_alloc(&de, &ep->fr_freelist);
```
Comment (jswaro) [inline prov/gni/include/gnix_ep.h:256]: Is it possible to get to a point where this is an endless loop?

File: prov/gni/src/gnix_msg.c [hunk 7]
```diff
@@ -1888,6 +1894,48 @@ static int __smsg_eager_msg_w_data(void *data, void *msg)
 	req = _gnix_match_tag(posted_queue, hdr->msg_tag, 0, FI_PEEK, NULL,
 			      &vc->peer_addr);
 	if (req) {
+		if (req->type == GNIX_FAB_RQ_MRECV) {
+
+			mrecv_req = req;
+			req = _gnix_fr_alloc(ep);
```
Comment (sungeunchoi) [inline prov/gni/src/gnix_msg.c]: It's confusing to me why you assign mrecv_req to req, rather than just allocate new fab request.  Is there less stuff you have to copy if you do it in that direction?  If not, I think it would be easier to follow if it was the other way around.

File: prov/gni/src/gnix_msg.c [hunk 8]
```diff
@@ -456,6 +439,29 @@ static int __recv_completion_src(
 	return FI_SUCCESS;
 }
 
+/*
+ * GNI provider generates a special CQE to indicate
+ * its releasing a FI_MULTI_RECV receive buffer back to
+ * the application.
+ */
```
Comment (jswaro) [inline prov/gni/src/gnix_msg.c]: Why do we have/need a special CQE? What part of the libfabric design or our implementation is lacking such that we need this special CQE?

File: prov/gni/src/gnix_msg.c [hunk 9]
```diff
@@ -1888,6 +1894,48 @@ static int __smsg_eager_msg_w_data(void *data, void *msg)
 	req = _gnix_match_tag(posted_queue, hdr->msg_tag, 0, FI_PEEK, NULL,
 			      &vc->peer_addr);
 	if (req) {
+		if (req->type == GNIX_FAB_RQ_MRECV) {
+
```
Comment (jswaro) [inline prov/gni/src/gnix_msg.c]: nit: This is a really long segment of code specific to 1 condition. Would you mind putting it into it's own subfunction?

File: prov/gni/src/gnix_msg.c [hunk 10]
```diff
@@ -1888,6 +1894,48 @@ static int __smsg_eager_msg_w_data(void *data, void *msg)
...
+			req->msg.recv_flags = mrecv_req->msg.recv_flags;
+			req->msg.recv_flags |= FI_MULTI_RECV;
+			req->msg.recv_info[0].recv_addr =
+				mrecv_req->msg.mr_buf_addr;
+			req->msg.recv_info[0].recv_len =
+				mrecv_req->msg.mr_space_left;
+			req->msg.cum_recv_len = mrecv_req->msg.mr_space_left;
+			req->user_context = mrecv_req->user_context;
+
+			req->msg.parent = mrecv_req;
```
Comment (jswaro) [inline prov/gni/src/gnix_msg.c]: This seems like a strange relationship.

File: prov/gni/src/gnix_msg.c [hunk 11]
```diff
@@ -1888,6 +1894,48 @@ static int __smsg_eager_msg_w_data(void *data, void *msg)
...
+			_gnix_ref_get(mrecv_req);
+
+			mrecv_req->msg.mr_space_left -= hdr->len;
```
Comment (jswaro) [inline prov/gni/src/gnix_msg.c]: You seem to follow two conventions. mrecv, and mr. Can we stick with one or the other and use it uniformly? 

I'd add that we already use mr to refer to memory registrations.

File: prov/gni/src/gnix_msg.c [hunk 12]
```diff
@@ -1888,6 +1894,48 @@ static int __smsg_eager_msg_w_data(void *data, void *msg)
...
+			mrecv_req->msg.mr_buf_addr += hdr->len;
+
+			if ((int64_t)mrecv_req->msg.mr_space_left  <
+				ep->min_multi_recv) {
+				_gnix_remove_tag(posted_queue, mrecv_req);
+				_gnix_ref_put(mrecv_req);
```
Comment (jswaro) [inline prov/gni/src/gnix_msg.c]: Is there a guarantee that all references will have been removed at this point?

File: prov/gni/src/gnix_msg.c [hunk 13]
```diff
@@ -2054,6 +2091,49 @@ static int __smsg_rndzv_start(void *data, void *msg)
 			      &vc->peer_addr);
 
 	if (req) {
+		if (req->type == GNIX_FAB_RQ_MRECV) {
```
Comment (jswaro) [inline prov/gni/src/gnix_msg.c:2112]: Isn't this basically duplicated code from above?

File: prov/gni/src/gnix_msg.c [hunk 14]
```diff
@@ -2527,12 +2583,12 @@ ssize_t _gnix_recv(struct gnix_fid_ep *ep, uint64_t buf, size_t len,
 			return -FI_EOPNOTSUPP;
 	}
 
-	match_flags = flags & (FI_CLAIM | FI_DISCARD | FI_PEEK);
-
 	ret = __gnix_msg_addr_lookup(ep, src_addr, &gnix_addr);
 	if (ret != FI_SUCCESS)
 		return ret;
```
Comment (jswaro) [inline prov/gni/src/gnix_msg.c:2573]: Why move the match_flags statement?

File: prov/gni/src/gnix_msg.c [hunk 15]
```diff
@@ -2743,13 +2777,112 @@ ssize_t _gnix_recv(struct gnix_fid_ep *ep, uint64_t buf, size_t len,
...
+	struct gnix_fab_req *mrecv_req = NULL;
+	struct gnix_address gnix_addr;
+	struct gnix_fid_mem_desc *md = NULL;
+	struct gnix_tag_storage *posted_queue = NULL;
+	struct gnix_tag_storage *unexp_queue = NULL;
+	uint64_t last_space_left;
+
+	assert(flags & FI_MULTI_RECV);
+
+	mrecv_req = _gnix_fr_alloc_w_cb(ep, __gnix_msg_mrecv_completion);
```
Comment (jswaro) [inline prov/gni/src/gnix_msg.c:2787]: _gnix_fr_alloc_w_cb could wrap _gnix_fr_alloc. Why doesn't it?

File: prov/gni/include/gnix_ep.h (hunk 6 above)
Comment (hppritcha) [reply prov/gni/include/gnix_ep.h:256]: I think this checking - and the point in ```_gnix_fl_alloc``` is coded to return -FI_EAGAIN may be a hold over from some previous way we were dealing with growing the free list and handling of multiple threads using the free list concurrently.  We probably could remove this loop from both fr alloc routines.  I'd rather do that in a separate PR though.

File: prov/gni/include/gnix_ep.h (hunk 3 above)
Comment (hppritcha) [reply prov/gni/include/gnix_ep.h]: correct.  I'll fix both fr allocate funtions.

File: prov/gni/include/gnix_ep.h (hunk 4 above)
Comment (hppritcha) [reply prov/gni/include/gnix_ep.h]: no

File: prov/gni/src/gnix_msg.c (hunk 8 above)
Comment (hppritcha) [reply prov/gni/src/gnix_msg.c]: this is one of the main things about this PR.  We have an out-of-order network so we may be filling different parts of the multi-receive out of order wrt to where they started in the buffer.  We do not know which transfer will be completed last if we are using rendezvous for some of the messages.  So hence the use of a special CQE to indicate that the buffer is 1) full and 2) all the outstanding message data from the various messages arriving in the buffer have been delivered.  The original design would only work correctly if all the messages coming in to the buffer were using the eager, SMSG path.

File: prov/gni/src/gnix_msg.c (hunk 10 above)
Comment (hppritcha) [reply prov/gni/src/gnix_msg.c]: in what way?  The mother is the multi recv request.  The children are all the "regular" receive requests that are being used to progress the actual receives.

File: prov/gni/src/gnix_msg.c (hunk 11 above)
Comment (hppritcha) [reply prov/gni/src/gnix_msg.c]: good point, I'll change the field names.

File: prov/gni/src/gnix_msg.c (hunk 7 above)
Comment (hppritcha) [reply prov/gni/src/gnix_msg.c]: We need to leave the original ```reg``` returned from ```_gnix_match_tag``` to stay in the posted queue if its not full, so I "save" that pointer by assigning ```mrecv_req``` to the pointer returned from the tag match function.  We also need to update the ```mr_space_left``` and ```mr_buf_addr```.  The new fab request is to track the individual "normal" receive.  Does this make sense?

File: prov/gni/src/gnix_msg.c (hunk 8 above)
Comment (jswaro) [reply prov/gni/src/gnix_msg.c]: In the documentation, you write 'separate' which is indicated in the fi_cq documentation as allowed. In this segment, you write special. Which is it? Are we following spec and providing a separate CQE for notifying the application that the buffer is gone, or is this a GNI provider specific special CQE?

Comment (hppritcha) [reply prov/gni/src/gnix_msg.c]: special == separate.  I'll change the wording in the comment

**Comment by hppritcha** [comment]
pushed a bunch of feedback commits.
